name: Discord Webhook

on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord messages
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          for i in {1..100}; do
            curl -H "Content-Type: application/json" \
              -d '{"content":"@everyone GET THE FUCK ONLINE","allowed_mentions":{"parse":["everyone"]}}' \
              "$WEBHOOK"
          done
